ARMOR_MOD_NAME = minetest.get_current_modname()
dofile(minetest.get_modpath(ARMOR_MOD_NAME).."/armor.lua")
dofile(minetest.get_modpath(ARMOR_MOD_NAME).."/leather.lua")
dofile(minetest.get_modpath(ARMOR_MOD_NAME).."/cloth.lua")
dofile(minetest.get_modpath(ARMOR_MOD_NAME)..'/copper.lua')
dofile(minetest.get_modpath(ARMOR_MOD_NAME).."/shields.lua")
